repository:
  base:
    url: http://localhost:9080/alfresco/
user:
  admin:
    password: admin
server:
  servlet:
    context-path: /
ajp:
  port: 8009
  timeout: 120000
rrd:
  path: remote-shared,remote,remote-agid
  skipmd5: true

ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt

mail:
  from:
    default: concorsi@agid.gov.it
  protocol:
    to: eprot1@pec.almaviva.it

hazelcast:
  members: 127.0.0.1
  port:
    autoincrement: false

  multicast:
    port: 12345
  instance:
    name: agid

cookie:
  secure: true

security:
  enable-csrf: true

attiva:
  protocol:
    application: true

timer:
  cron:
    protocol: 0 0 2 * * *

block:
  submit:
    employee: false

agid-login:
  name: AGID@login
  url: https://login.agid.gov.it
  auth: ${agid-login.url}/auth
  logout: ${agid-login.url}/session/end
  redirect_uri: must_be_set
  post_logout_redirect_uri: must_be_set
  client_id: secret
  client_secret: secret
  response_type: code
  scope: openid profile