repository:
  base:
    url: http://localhost:9080/alfresco/
user:
  admin:
    password: admin
server:
  servlet:
    context-path: /
rrd:
  path: remote-shared,remote,remote-agid
  skipmd5: true

ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt

mail:
  from:
    default: concorsi@agid.gov.it

hazelcast:
  port: 1234
  autoincrement: false
  multicast:
    port: 12345
  instance:
    name: agid

attiva:
  protocol:
    application: false

spid:
  enable: true
  issuer:
    entityid: https://miauri.it
  destination: http://localhost:8080/spid/send-response