repository:
  base:
    url: http://localhost:9080/alfresco/
user:
  admin:
    password: admin
server:
  servlet:
    context-path: /
rrd:
  path: remote-shared,remote,remote-agid
  skipmd5: true

ipa:
  url:
    base: https://www.indicepa.gov.it/public-services/opendata-read-service.php
    amministrazioni: ${ipa.url.base}?dstype=FS&filename=amministrazioni.txt

mail:
  from:
    default: concorsi@agid.gov.it

hazelcast:
  port: 1234
  autoincrement: false
  multicast:
    port: 12345
  instance:
    name: agid

attiva:
  protocol:
    application: false

feign:
  httpclient:
    disableSslValidation: true

agid-login:
  url: https://login.agid.gov.it
  auth: ${agid-login.url}/auth
  redirect_uri: must_be_set
  client_id: secret
  client_secret: secret
  response_type: code
  scope: openid profile